---
language: rust
script:
- "./_test/check-exercises.sh"
- "bash ./_test/ensure-lib-src-rs-exist.sh"
- "sh ./_test/ensure-stubs-compile.sh"
- "sh ./_test/count-ignores.sh"
- "./bin/fetch-configlet"
- "./_test/check-configlet-fmt.sh"
- "sh ./_test/ensure-readmes-are-updated.sh"
- "./bin/configlet lint ."
- "./_test/verify-exercise-difficulties.sh"
- "./_test/check-exercises-for-authors.sh"
- "sh ./_test/check-exercise-crate.sh"
sudo: false
rust:
  - stable
  - beta
env:
  - DENYWARNINGS=
  - DENYWARNINGS=1
matrix:
  include:
    - rust: nightly
      env: BENCHMARK=1
      script: "./_test/check-exercises.sh"
  allow_failures:
    - rust: nightly
    - rust: beta
      env: DENYWARNINGS=1
