[canonical-tests]

# List of scores
1035eb93-2208-4c22-bab8-fef06769a73c = false

# Latest score
6aa5dbf5-78fa-4375-b22c-ffaa989732d2 = false

# Personal best
b661a2e1-aebf-4f50-9139-0fb817dd12c6 = false

# Personal top three from a list of scores
3d996a97-c81c-4642-9afc-80b80dc14015 = false

# Personal top highest to lowest
1084ecb5-3eb4-46fe-a816-e40331a4e83a = false

# Personal top when there is a tie
e6465b6b-5a11-4936-bfe3-35241c4f4f16 = false

# Personal top when there are less than 3
f73b02af-c8fd-41c9-91b9-c86eaa86bce2 = false

# Personal top when there is only one
16608eae-f60f-4a88-800e-aabce5df2865 = false
