[canonical-tests]

# Smallest perfect number is classified correctly
"163e8e86-7bfd-4ee2-bd68-d083dc3381a3" = false

# Medium perfect number is classified correctly
"169a7854-0431-4ae0-9815-c3b6d967436d" = false

# Large perfect number is classified correctly
"ee3627c4-7b36-4245-ba7c-8727d585f402" = false

# Smallest abundant number is classified correctly
"80ef7cf8-9ea8-49b9-8b2d-d9cb3db3ed7e" = false

# Medium abundant number is classified correctly
"3e300e0d-1a12-4f11-8c48-d1027165ab60" = false

# Large abundant number is classified correctly
"ec7792e6-8786-449c-b005-ce6dd89a772b" = false

# Smallest prime deficient number is classified correctly
"e610fdc7-2b6e-43c3-a51c-b70fb37413ba" = false

# Smallest non-prime deficient number is classified correctly
"0beb7f66-753a-443f-8075-ad7fbd9018f3" = false

# Medium deficient number is classified correctly
"1c802e45-b4c6-4962-93d7-1cad245821ef" = false

# Large deficient number is classified correctly
"47dd569f-9e5a-4a11-9a47-a4e91c8c28aa" = false

# Edge case (no factors other than itself) is classified correctly
"a696dec8-6147-4d68-afad-d38de5476a56" = false

# Zero is rejected (not a natural number)
"72445cee-660c-4d75-8506-6c40089dc302" = false

# Negative integer is rejected (not a natural number)
"2d72ce2c-6802-49ac-8ece-c790ba3dae13" = false
