[canonical-tests]

# zero
5d22a120-ba0c-428c-bd25-8682235d83e8 = false

# one
9b5eed77-dbf6-439d-b920-3f7eb58928f6 = false

# fourteen
7c499be1-612e-4096-a5e1-43b2f719406d = false

# twenty
f541dd8e-f070-4329-92b4-b7ce2fcf06b4 = false

# twenty-two
d78601eb-4a84-4bfa-bf0e-665aeb8abe94 = false

# one hundred
e417d452-129e-4056-bd5b-6eb1df334dce = false

# one hundred twenty-three
d6924f30-80ba-4597-acf6-ea3f16269da8 = false

# one thousand
3d83da89-a372-46d3-b10d-de0c792432b3 = false

# one thousand two hundred thirty-four
865af898-1d5b-495f-8ff0-2f06d3c73709 = false

# one million
b6a3f442-266e-47a3-835d-7f8a35f6cf7f = false

# one million two thousand three hundred forty-five
2cea9303-e77e-4212-b8ff-c39f1978fc70 = false

# one billion
3e240eeb-f564-4b80-9421-db123f66a38f = false

# a big number
9a43fed1-c875-4710-8286-5065d73b8a9e = false

# numbers below zero are out of range
49a6a17b-084e-423e-994d-a87c0ecc05ef = false

# numbers above 999,999,999,999 are out of range
4d6492eb-5853-4d16-9d34-b0f61b261fd9 = false
