[canonical-tests]

# empty sentence
"64f61791-508e-4f5c-83ab-05de042b0149" = false

# perfect lower case
"74858f80-4a4d-478b-8a5e-c6477e4e4e84" = false

# only lower case
"61288860-35ca-4abe-ba08-f5df76ecbdcd" = false

# missing the letter 'x'
"6564267d-8ac5-4d29-baf2-e7d2e304a743" = false

# missing the letter 'h'
"c79af1be-d715-4cdb-a5f2-b2fa3e7e0de0" = false

# with underscores
"d835ec38-bc8f-48e4-9e36-eb232427b1df" = false

# with numbers
"8cc1e080-a178-4494-b4b3-06982c9be2a8" = false

# missing letters replaced by numbers
"bed96b1c-ff95-45b8-9731-fdbdcb6ede9a" = false

# mixed case and punctuation
"938bd5d8-ade5-40e2-a2d9-55a338a01030" = false

# case insensitive
"2577bf54-83c8-402d-a64b-a2c0f7bb213a" = false
