[canonical-tests]

# zero
"35c9db2e-f781-4c52-b73b-8e76427defd0" = false

# arbitrary single byte
"be44d299-a151-4604-a10e-d4b867f41540" = false

# largest single byte
"ea399615-d274-4af6-bbef-a1c23c9e1346" = false

# smallest double byte
"77b07086-bd3f-4882-8476-8dcafee79b1c" = false

# arbitrary double byte
"63955a49-2690-4e22-a556-0040648d6b2d" = false

# largest double byte
"29da7031-0067-43d3-83a7-4f14b29ed97a" = false

# smallest triple byte
"3345d2e3-79a9-4999-869e-d4856e3a8e01" = false

# arbitrary triple byte
"5df0bc2d-2a57-4300-a653-a75ee4bd0bee" = false

# largest triple byte
"f51d8539-312d-4db1-945c-250222c6aa22" = false

# smallest quadruple byte
"da78228b-544f-47b7-8bfe-d16b35bbe570" = false

# arbitrary quadruple byte
"11ed3469-a933-46f1-996f-2231e05d7bb6" = false

# largest quadruple byte
"d5f3f3c3-e0f1-4e7f-aad0-18a44f223d1c" = false

# smallest quintuple byte
"91a18b33-24e7-4bfb-bbca-eca78ff4fc47" = false

# arbitrary quintuple byte
"5f34ff12-2952-4669-95fe-2d11b693d331" = false

# maximum 32-bit integer input
"7489694b-88c3-4078-9864-6fe802411009" = false

# two single-byte values
"f9b91821-cada-4a73-9421-3c81d6ff3661" = false

# two multi-byte values
"68694449-25d2-4974-ba75-fa7bb36db212" = false

# many multi-byte values
"51a06b5c-de1b-4487-9a50-9db1b8930d85" = false

# one byte
"baa73993-4514-4915-bac0-f7f585e0e59a" = false

# two bytes
"72e94369-29f9-46f2-8c95-6c5b7a595aee" = false

# three bytes
"df5a44c4-56f7-464e-a997-1db5f63ce691" = false

# four bytes
"1bb58684-f2dc-450a-8406-1f3452aa1947" = false

# maximum 32-bit integer
"cecd5233-49f1-4dd1-a41a-9840a40f09cd" = false

# incomplete sequence causes error
"e7d74ba3-8b8e-4bcb-858d-d08302e15695" = false

# incomplete sequence causes error, even if value is zero
"aa378291-9043-4724-bc53-aca1b4a3fcb6" = false

# multiple values
"a91e6f5a-c64a-48e3-8a75-ce1a81e0ebee" = false
