[canonical-tests]

# zero pieces
e974b73e-7851-484f-8d6d-92e07fe742fc = false

# one piece
2fcd5f5e-8b82-4e74-b51d-df28a5e0faa4 = false

# two pieces
d9d0a8a1-d933-46e2-aa94-eecf679f4b0e = false

# three pieces
c95ef757-5e94-4f0d-a6cb-d2083f5e5a83 = false

# full proverb
433fb91c-35a2-4d41-aeab-4de1e82b2126 = false

# four pieces modernized
c1eefa5a-e8d9-41c7-91d4-99fab6d6b9f7 = false
