[canonical-tests]

# finds the largest product if span equals length
"7c82f8b7-e347-48ee-8a22-f672323324d4" = false

# can find the largest product of 2 with numbers in order
"88523f65-21ba-4458-a76a-b4aaf6e4cb5e" = false

# can find the largest product of 2
"f1376b48-1157-419d-92c2-1d7e36a70b8a" = false

# can find the largest product of 3 with numbers in order
"46356a67-7e02-489e-8fea-321c2fa7b4a4" = false

# can find the largest product of 3
"a2dcb54b-2b8f-4993-92dd-5ce56dece64a" = false

# can find the largest product of 5 with numbers in order
"673210a3-33cd-4708-940b-c482d7a88f9d" = false

# can get the largest product of a big number
"02acd5a6-3bbf-46df-8282-8b313a80a7c9" = false

# reports zero if the only digits are zero
"76dcc407-21e9-424c-a98e-609f269622b5" = false

# reports zero if all spans include zero
"6ef0df9f-52d4-4a5d-b210-f6fae5f20e19" = false

# rejects span longer than string length
"5d81aaf7-4f67-4125-bf33-11493cc7eab7" = false

# reports 1 for empty string and empty product (0 span)
"06bc8b90-0c51-4c54-ac22-3ec3893a079e" = false

# reports 1 for nonempty string and empty product (0 span)
"3ec0d92e-f2e2-4090-a380-70afee02f4c0" = false

# rejects empty string and nonzero span
"6d96c691-4374-4404-80ee-2ea8f3613dd4" = false

# rejects invalid character in digits
"7a38f2d6-3c35-45f6-8d6f-12e6e32d4d74" = false

# rejects negative span
"5fe3c0e5-a945-49f2-b584-f0814b4dd1ef" = false
